### PR TITLE
Fix handling of $default stage to support HTTP API

### LINKED ISSUE #39: Http API
From https://github.com/developmentseed/cogeo-mosaic-tiler/issues/1

It would be nice to optionally support HTTP APIs in `lambda-proxy` in addition to the existing REST API. HTTP APIs are cheaper at $1/1M instead of $3.50/1M, and often a there's no need to use a REST API. ([List of differences here](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html)).

For a simple `serverless.yml`, you can just change

```yml
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true
```
to
```yml
    events:
      - httpApi:
          path: /{proxy+}
          method: '*'
          cors: true
```

Most endpoints work fine, but I think endpoints that rely on relative URLs don't, i.e. `/docs`:
image

I'm gonna try to dig into this more

### PR DESCRIPTION
**Pull request by kylebarron**
Closes #39 

Working relative paths:
image

Note that there's lots of scaffolding in this pr to help test that it works, but the only actual change is [here](https://github.com/vincentsarago/lambda-proxy/pull/40/files#diff-ebb942df33af9c7c3fea49c4478b5338R165-R167):

```py
    def prefix(self):
        """Return the API prefix."""
        if self.apigw_stage:
            if self.apigw_stage == '/$default':
                return self.api_prefix

            return self.apigw_stage + self.api_prefix
```

### CODE REVIEW

**Comment by kylebarron** [comment]
I did a test with the `app.py` from the example and everything seems to work fine. (Though with the unmodified `app.py` file `/json` and `/binary` don't work because the catch-all `/<string:user>` is too high in the file and overrides each endpoint.)

I'm assuming you won't want to merge this PR as-is because of the extra files. I can create a separate PR if you want, or you can just make the modification above yourself if you approve.

**Comment by kylebarron** [comment]
Also, I can't tell.. are you using regex to parse the input [`event.json`](https://github.com/awsdocs/aws-lambda-developer-guide/blob/master/sample-apps/nodejs-apig/event.json)?

**Comment by vincentsarago** [comment]
> to parse the input event.json?

I'm not sure to understand

**Comment by kylebarron** [comment]
I suppose `event` is declared to be a `Dict`... I was just confused why you use so many complex regexes
https://github.com/vincentsarago/lambda-proxy/blob/b5ee68b65544765648d532659a8412b33cf8fc07/lambda_proxy/proxy.py#L21-L57

**Comment by vincentsarago** [comment]
`params_expr`, `param_pattern`, `regex_pattern` and `_path_to_regex()` are only to parse the routes and translate event path. It's complex but I'm sure it is still a simple solution ;-)

**Comment by kylebarron** [comment]
Ok well I'll leave those regexes to you!

**Comment by vincentsarago** [comment]
Hey @kylebarron thanks for the PR. I think we can open a new BR with just the change and also update tests and documentation!

**Pull request closed without merging**
